// action types
export const SET_STYLE = 'SET_STYLE';
export const SET_DESIGN = 'SET_DESIGN';
export const SET_DESIGN_OPTIONS = 'SET_DESIGN_OPTIONS';
export const SET_CUSTOMIZATIONS = 'SET_CUSTOMIZATIONS';
export const SET_DESIGN_COMPLETE = 'SET_DESIGN_COMPLETE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
